macro PrintLabelAddress(label)
    print "  <label>: 0x",hex(snestopc(<label>)),","
endmacro

print ""
print "const BOSSES = {"
%PrintLabelAddress(DoorToKraidBoss)
%PrintLabelAddress(DoorToPhantoonBoss)
%PrintLabelAddress(DoorToDraygonBoss)
%PrintLabelAddress(DoorToRidleyBoss)
print "  //"
%PrintLabelAddress(DoorVectorToKraid)
%PrintLabelAddress(DoorVectorToPhantoon)
%PrintLabelAddress(DoorVectorToDraygon)
%PrintLabelAddress(DoorVectorToRidley)
print "  //"
%PrintLabelAddress(DoorVectorTeleportToKraid)
%PrintLabelAddress(DoorVectorTeleportToPhantoon)
%PrintLabelAddress(DoorVectorTeleportToDraygon)
%PrintLabelAddress(DoorVectorTeleportToRidley)
print "  //"
%PrintLabelAddress(DoorFromKraidRoom)
%PrintLabelAddress(DoorFromPhantoonRoom)
%PrintLabelAddress(DoorFromDraygonRoom)
%PrintLabelAddress(DoorFromRidleyRoom)
print "  //"
%PrintLabelAddress(DoorVectorToPreKraid)
%PrintLabelAddress(DoorVectorToPrePhantoon)
%PrintLabelAddress(DoorVectorToPreDraygon)
%PrintLabelAddress(DoorVectorToPreRidley)
print "  //"
%PrintLabelAddress(DoorVectorTeleportToPreKraid)
%PrintLabelAddress(DoorVectorTeleportToPrePhantoon)
%PrintLabelAddress(DoorVectorTeleportToPreDraygon)
%PrintLabelAddress(DoorVectorTeleportToPreRidley)
print "};"
print ""
print "const AREAS = {"
%PrintLabelAddress(Door_RetroPBs)
%PrintLabelAddress(Door_GreenHills)
%PrintLabelAddress(Door_Moat)
%PrintLabelAddress(Door_Ocean)
%PrintLabelAddress(Door_G4)
%PrintLabelAddress(Door_Tourian)
%PrintLabelAddress(Door_Kago)
%PrintLabelAddress(Door_GreenElevator)
%PrintLabelAddress(Door_Crabs)
%PrintLabelAddress(Door_RedElevator)
%PrintLabelAddress(Door_HighwayExit)
%PrintLabelAddress(Door_Highway)
%PrintLabelAddress(Door_NoobBridge)
%PrintLabelAddress(Door_RedTower)
%PrintLabelAddress(Door_MaridiaEscape)
%PrintLabelAddress(Door_RedFish)
%PrintLabelAddress(Door_MaridiaTube)
%PrintLabelAddress(Door_MainStreet)
%PrintLabelAddress(Door_KraidEntry)
%PrintLabelAddress(Door_ElevatorEntry)
%PrintLabelAddress(Door_AboveKraid)
%PrintLabelAddress(Door_MaridiaMap)
%PrintLabelAddress(Door_KraidMouth)
%PrintLabelAddress(Door_KraidsLair)
%PrintLabelAddress(Door_CrocEntry)
%PrintLabelAddress(Door_Croc)
%PrintLabelAddress(Door_SingleChamber)
%PrintLabelAddress(Door_Muskateers)
%PrintLabelAddress(Door_LavaDive)
%PrintLabelAddress(Door_RidleyMouth)
%PrintLabelAddress(Door_PreAqueduct)
%PrintLabelAddress(Door_Aqueduct)
print "  //"
%PrintLabelAddress(DoorVectorToRetroPBs)
%PrintLabelAddress(DoorVectorToGreenHills)
%PrintLabelAddress(DoorVectorToMoat)
%PrintLabelAddress(DoorVectorToOcean)
%PrintLabelAddress(DoorVectorToG4)
%PrintLabelAddress(DoorVectorToTourian)
%PrintLabelAddress(DoorVectorToKago)
%PrintLabelAddress(DoorVectorToGreenElevator)
%PrintLabelAddress(DoorVectorToCrabs)
%PrintLabelAddress(DoorVectorToRedElevator)
%PrintLabelAddress(DoorVectorToHighwayExit)
%PrintLabelAddress(DoorVectorToHighway)
%PrintLabelAddress(DoorVectorToNoobBridge)
%PrintLabelAddress(DoorVectorToRedTower)
%PrintLabelAddress(DoorVectorToMaridiaEscape)
%PrintLabelAddress(DoorVectorToRedFish)
%PrintLabelAddress(DoorVectorToMaridiaTube)
%PrintLabelAddress(DoorVectorToMainStreet)
%PrintLabelAddress(DoorVectorToKraidEntry)
%PrintLabelAddress(DoorVectorToElevatorEntry)
%PrintLabelAddress(DoorVectorToAboveKraid)
%PrintLabelAddress(DoorVectorToMaridiaMap)
%PrintLabelAddress(DoorVectorToKraidMouth)
%PrintLabelAddress(DoorVectorToKraidsLair)
%PrintLabelAddress(DoorVectorToCrocEntry)
%PrintLabelAddress(DoorVectorToCroc)
%PrintLabelAddress(DoorVectorToSingleChamber)
%PrintLabelAddress(DoorVectorToMuskateers)
%PrintLabelAddress(DoorVectorToLavaDive)
%PrintLabelAddress(DoorVectorToRidleyMouth)
%PrintLabelAddress(DoorVectorToPreAqueduct)
%PrintLabelAddress(DoorVectorToAqueduct)
print "  //"
%PrintLabelAddress(DoorVectorTeleportToRetroPBs)
%PrintLabelAddress(DoorVectorTeleportToGreenHills)
%PrintLabelAddress(DoorVectorTeleportToMoat)
%PrintLabelAddress(DoorVectorTeleportToOcean)
%PrintLabelAddress(DoorVectorTeleportToG4)
%PrintLabelAddress(DoorVectorTeleportToTourian)
%PrintLabelAddress(DoorVectorTeleportToKago)
%PrintLabelAddress(DoorVectorTeleportToGreenElevator)
%PrintLabelAddress(DoorVectorTeleportToCrabs)
%PrintLabelAddress(DoorVectorTeleportToRedElevator)
%PrintLabelAddress(DoorVectorTeleportToHighwayExit)
%PrintLabelAddress(DoorVectorTeleportToHighway)
%PrintLabelAddress(DoorVectorTeleportToNoobBridge)
%PrintLabelAddress(DoorVectorTeleportToRedTower)
%PrintLabelAddress(DoorVectorTeleportToMaridiaEscape)
%PrintLabelAddress(DoorVectorTeleportToRedFish)
%PrintLabelAddress(DoorVectorTeleportToMaridiaTube)
%PrintLabelAddress(DoorVectorTeleportToMainStreet)
%PrintLabelAddress(DoorVectorTeleportToKraidEntry)
%PrintLabelAddress(DoorVectorTeleportToElevatorEntry)
%PrintLabelAddress(DoorVectorTeleportToAboveKraid)
%PrintLabelAddress(DoorVectorTeleportToMaridiaMap)
%PrintLabelAddress(DoorVectorTeleportToKraidMouth)
%PrintLabelAddress(DoorVectorTeleportToKraidsLair)
%PrintLabelAddress(DoorVectorTeleportToCrocEntry)
%PrintLabelAddress(DoorVectorTeleportToCroc)
%PrintLabelAddress(DoorVectorTeleportToSingleChamber)
%PrintLabelAddress(DoorVectorTeleportToMuskateers)
%PrintLabelAddress(DoorVectorTeleportToLavaDive)
%PrintLabelAddress(DoorVectorTeleportToRidleyMouth)
%PrintLabelAddress(DoorVectorTeleportToPreAqueduct)
%PrintLabelAddress(DoorVectorTeleportToAqueduct)
print "};"
print ""